services:
  - type: web
    name: history-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: ваш_токен
      - key: DATABASE_URL
        value: посилання_на_postgresql
      - key: RENDER_EXTERNAL_HOSTNAME
        generateValue: true
