services:
  - type: web
    name: telegram-history-bot
    env: python
    buildCommand: ""
    startCommand: python bot.py
    region: oregon
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
